feat: action pipeline for account service
muhlba91/fh-burgenland-bswe-assignment-infrastructure pull request #120
Opened 2024-12-06 15:23 UTC by AndreasDoetzl

# Adding the CI/CD pipline for the account repo of group k

test: Unit tests 
conform: 
spectral: 
yamllint: checks the .yaml files
build: builds the project

## Issue Reference https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/issues/15

- fixes #15

## Type of change

- [ x] CI/CD pipline change

2024-12-06 21:59 UTC, muhlba91 requested changes
see comment and please apply to all required checks as per your pipeline in https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/blob/main/.github/workflows/pipeline.yaml

2024-12-06 21:59 UTC, muhlba91 commented on assets/data_ws2024.yaml
> +      - test
GitHub is odd in this case and requires the `name` instead of the `id/key`.
in your case the `id/key` is `test` (https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/blob/main/.github/workflows/pipeline.yaml#L10) but the `name` is `Unit Tests` (https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/blob/main/.github/workflows/pipeline.yaml#L12)

2024-12-07 08:03 UTC, AndreasDoetzl commented on assets/data_ws2024.yaml
> +      - test
This is really weird. I wanted to double check it with another group but have not access to their repo. ;-)

2024-12-07 08:15 UTC, muhlba91 requested changes

2024-12-07 08:15 UTC, muhlba91 commented on assets/data_ws2024.yaml
> +      - Unit Tests
you use a matrix job here to pass in the java version (https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/blob/main/.github/workflows/pipeline.yaml#L16)
check one of your pull requests - e.g. https://github.com/fhburgenland-bswe/swm2-ws2024-group-k-accounts/pull/34 -> as you can see the name has ` (23)` appended.
the name must match this. please update `Unit Tests` and `Build and Package Application` where you have matrix jobs defined.

for example, looking at the previously mentioned pull request, you have a job `Pipeline / Unit Tests (23) (pull_request)`. this translates to `Unit Tests (23)` when setting required checks.
yes, GitHub is a bit odd because once you change the matrix, you have to update the required checks.

2024-12-09 17:13 UTC, AndreasDoetzl commented on assets/data_ws2024.yaml
> +      - Unit Tests
I removed the matrix job in our project. This workflow is very frustrating and took me much too long to get this done.

2024-12-09 17:55 UTC, muhlba91 commented on assets/data_ws2024.yaml
> +      - Unit Tests
yeah, with matrix jobs it's pretty counterintuitive at first but if you get your head around it, it's getting better... 🙂

the workflow in your repository looked pretty OK to me, as well as your pull request here (after the first iteration with the name confusion). keep up the work, and once the first workflow is done, the other repositories are waaaayyyy faster and easier. 😉

2024-12-09 17:56 UTC, muhlba91 approved these changes
keep up the good work! and once the first workflow is done, the other repositories are waaaayyyy faster and easier. 🙂

2024-12-09 17:56 UTC, merged