feat: action pipeline for infrastructure - group-a
muhlba91/fh-burgenland-bswe-assignment-infrastructure pull request #66
Opened 2024-11-10 13:20 UTC by janjungwirth

relates: https://github.com/fhburgenland-bswe/swm2-ws2024-group-a-accounts/issues/10

CheckstyleMain: for checking the defined style guilde
Test: Unit tests need to run green
bootjar: Project is buildable
Spectral Linter: checks .yaml files
YAMLLint: as well checks .yaml files

2024-11-10 14:48 UTC, muhlba91 approved these changes

2024-11-10 14:49 UTC, muhlba91 commented
@janjungwirth please fix the CI errors:
https://github.com/muhlba91/fh-burgenland-bswe-assignment-infrastructure/actions/runs/11765518997/job/32773211467?pr=66#step:6:9
https://github.com/muhlba91/fh-burgenland-bswe-assignment-infrastructure/actions/runs/11765518997/job/32773211915?pr=66#step:5:6

2024-11-10 14:52 UTC, muhlba91 requested changes
please fix the CI errors:
https://github.com/muhlba91/fh-burgenland-bswe-assignment-infrastructure/actions/runs/11765518997/job/32773211467?pr=66#step:6:9
https://github.com/muhlba91/fh-burgenland-bswe-assignment-infrastructure/actions/runs/11765518997/job/32773211915?pr=66#step:5:6

2024-11-14 17:19 UTC, closed without merging

2024-11-14 17:27 UTC, janjungwirth commented
please check pr #74 for the requested changes.